name: Build

on:
  workflow_dispatch:
    inputs:
      runner:
        default: "ubuntu-latest"
        description: "runner"
        type: choice
        options:
          - self-hosted
          - ubuntu-latest
          - windows-latest
          - k8s
        required: true

jobs:
  build:
    runs-on: ${{inputs.runner || 'ubuntu-latest'}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check files
        run: |
          printf "\n\n"

          printf "\e[93m%s\e[0m\n" \
            "RUNNER_WORKSPACE:     \"${RUNNER_WORKSPACE}\"" \
            "GITHUB_WORKSPACE:     \"${GITHUB_WORKSPACE}\"" \
            "GITHUB_ACTION_PATH:   \"${GITHUB_ACTION_PATH}\"" \
            "---                   ---" \
            "gh_token:             \"${GITHUB_TOKEN::8}****************\"" \
            "---                   ---"

          printf "\n\n"

          pwd
          tree -ahI ".git" --dirsfirst --du
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Selkies Docker image
        run: |
          docker build \
            --progress plain \
            --tag "selkies" \
            - <"selkies.dockerfile"
        shell: bash

      - name: Extract /build-out directory from Selkies image
        run: |
          docker create \
            --name "tmp_container" \
            "selkies"

          docker cp \
            "tmp_container:/build-out" \
            "./build-out"

          docker rm tmp_container
        shell: bash

      - name: Create Selkies dashboards tar archive
        run: |
          tar -zcvf "selkies-dashboards.tar.gz" \
            -C build-out \
            $(find build-out -maxdepth 1 -type d -name 'selkies-dashboard*' -printf '%f\n')
        shell: bash

      - name: Create xvfb fix tar archive
        run: |
          tar -zcvf "xvfb-fix.tar.gz" \
            -C build-out \
            xvfb-fix
        shell: bash

      - name: Create Release.md file
        run: |
          cat <<EOF >"release.md"
          ## Selkies
          ### Files:
            - selkies-dashboards.tar.gz
            - xvfb-fix.tar.gz
          EOF
        shell: bash

      - name: gh release create v0.0.2
        run: |
          gh release view "v0.0.2" &>/dev/null && gh release delete "v0.0.2"

          gh release create "v0.0.2" \
            --title "v0.0.2" \
            --notes-file "release.md" \
            --generate-notes \
            *.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}